DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS people;
DROP TABLE IF EXISTS cars;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  account VARCHAR(250) NOT NULL,
  mail VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS people (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  firstName VARCHAR(250) NOT NULL,
  lastName VARCHAR(250) NOT NULL,
  age INT
);

CREATE TABLE IF NOT EXISTS cars (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  factory VARCHAR(250) NOT NULL,
  name VARCHAR(250) NOT NULL,
  power INT,
  type VARCHAR(250) NOT NULL
);

